# Generated by Django 4.2.4 on 2023-09-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_bodyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyinfo',
            name='gender',
            field=models.BooleanField(default=False),
        ),
    ]
