# Generated by Django 4.2.4 on 2023-09-04 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_bodyinfo_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=20, verbose_name='記事名稱')),
                ('description', models.TextField(blank=True, null=True, verbose_name='說明')),
                ('note_type', models.CharField(choices=[('NOTE', '一般記事'), ('INCOME', '收入'), ('EXPENSE', '支出')], max_length=10)),
                ('money', models.IntegerField(default=0)),
                ('note_date', models.DateField(verbose_name='日期')),
                ('rec_time', models.DateTimeField(auto_now_add=True, verbose_name='記錄時間')),
            ],
        ),
    ]
