# Generated by Django 4.2.4 on 2023-09-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_notetype_alter_dailynote_note_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='mytask',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
