# Generated by Django 4.2.4 on 2023-09-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_mytask_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=20, verbose_name='貨幣名稱')),
                ('rate', models.FloatField(verbose_name='匯率')),
            ],
        ),
        migrations.AlterField(
            model_name='bodyinfo',
            name='gender',
            field=models.BooleanField(default=False, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='bodyinfo',
            name='height',
            field=models.FloatField(verbose_name='身高'),
        ),
        migrations.AlterField(
            model_name='bodyinfo',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='bodyinfo',
            name='weight',
            field=models.FloatField(verbose_name='體重'),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='money',
            field=models.IntegerField(default=0, verbose_name='金額'),
        ),
        migrations.AlterField(
            model_name='dailynote',
            name='note_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.notetype', verbose_name='記事類別'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='封存狀態'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='done',
            field=models.BooleanField(default=False, verbose_name='完成狀態'),
        ),
        migrations.AlterField(
            model_name='mytask',
            name='item',
            field=models.CharField(max_length=200, verbose_name='任務名稱'),
        ),
    ]
