# Generated by Django 4.2.4 on 2023-09-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='照片名稱'),
            preserve_default=False,
        ),
    ]
