# Generated by Django 4.2.4 on 2023-10-10 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=20, verbose_name='餐點')),
                ('food_type', models.CharField(choices=[('早餐', '早餐'), ('午餐', '午餐'), ('晚餐', '晚餐'), ('宵夜', '宵夜'), ('點心', '點心')], max_length=5, verbose_name='用餐類別')),
                ('score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='評分')),
                ('review', models.TextField(default='無', verbose_name='評論')),
                ('photo', models.ImageField(upload_to='foodreview', verbose_name='照片')),
            ],
        ),
    ]
