# Generated by Django 4.2.4 on 2023-09-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBabe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='相片')),
                ('vote', models.PositiveIntegerField(default=0, verbose_name='選票')),
            ],
        ),
    ]
